### ISSUE TITLE
Content missing on public dashboard page (which is a prominent link on the homepage)

### ISSUE THREAD

**Issue by yonasb** [africa-covid-19-response-toolkit/ethiocovid19rt.com#11]
https://ethiocovid19rt.com/projects/public-awareness

![Screen Shot 2020-04-25 at 2 37 13 PM](https://user-images.githubusercontent.com/1302071/80291430-5ee56e00-8702-11ea-89b4-b722704c5ea8.png)

**Comment by nabebe** [comment]
updated
