### ISSUE TITLE
partnership note was note updated [second attempt]

### ISSUE THREAD

**Issue by slakew** [africa-covid-19-response-toolkit/ethiocovid19rt.com#24]
I made an issue previously to update the partnership note to reflect the new language and although it was marked as resolved, the text has not been updated.

Please find the updated language here: here:https://docs.google.com/document/d/1nac1T3geXMBQ_4y078yzVUEFdJOGPRgmRSvRbR9lolg/edit

**Comment by nabebe** [comment]
Already updated on the next release. Will be out on the new version on Monday.

-- staged on the dev branch

**Comment by nabebe** [comment]
Already updated on the next release. Will be out on the new version on Monday.

-- staged on the dev branch
