### ISSUE TITLE
Add one more carousel item for the “About ECRT”

### ISSUE THREAD

**Issue by nabebe** [africa-covid-19-response-toolkit/ethiocovid19rt.com#26]
Header: Who we are
Text: On March 21st, we started off as a Slack channel of 4 software engineers working on building digital tools to help the Ethiopian Ministry of Health (MoH) track COVID-19 cases. By March 25th we had grown to a global volunteer network of more than 1600 people, working on over 15+ open source projects. A few of our current initiatives and activities include; creating a database for case tracking, developing public awareness campaigns, building bots, facilitating enhanced delivery logistics, retrofitting underutilized buildings into treatment centers, and responding to many other needs to combat COVID-19 in Africa.
Image:
Button Link: Links to the about us page

**Comment by gedion** [comment]
https://github.com/africa-covid-19-response-toolkit/ethiocovid19rt.com/pull/34

**Comment by gedion** [comment]
PR ready https://github.com/africa-covid-19-response-toolkit/ethiocovid19rt.com/issues/26
